/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f429xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MASTER_ADDR		0x60U
#define SLAVE_ADDR		0x01U

void delay()
{
	for (volatile uint32_t i = 0; i < 250000; i++);
}

// Data transfer
// [7:4]	not used
// [3:1]	led number
// [0]		on or off
uint8_t on1 = 0x0U, on2 = 0x2U, on3 = 0x4U, on4 = 0x6U, on5 = 0x8;

GPIO_Handle_t Btn1, Btn2, Btn3, Btn4, Btn5;
GPIO_Handle_t Led;
I2C_Handle_t I2C2Handle;

// Btn1		PC8
// Btn2		PC10
// Btn3		PC12
// Btn4		PG2
// Btn5		PD7

void Init_GPIO_Buttons(void)
{
	memset(&Btn1, 0, sizeof(Btn1));
	memset(&Btn2, 0, sizeof(Btn2));
	memset(&Btn3, 0, sizeof(Btn3));
	memset(&Btn4, 0, sizeof(Btn4));
	memset(&Btn5, 0, sizeof(Btn5));

	// Buttons
	Btn1.pGPIOx = GPIOC;
	Btn1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_8;
	Btn1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	Btn1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;
	GPIO_PClkControl(GPIOC, ENABLE);
	GPIO_Init(&Btn1);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);

	Btn2.pGPIOx = GPIOC;
	Btn2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_10;
	Btn2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	Btn2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;
	GPIO_PClkControl(GPIOC, ENABLE);
	GPIO_Init(&Btn2);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);

	Btn3.pGPIOx = GPIOC;
	Btn3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_12;
	Btn3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	Btn3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;
	GPIO_PClkControl(GPIOC, ENABLE);
	GPIO_Init(&Btn3);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);


	Btn4.pGPIOx = GPIOG;
	Btn4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_2;
	Btn4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	Btn4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;
	GPIO_PClkControl(GPIOG, ENABLE);
	GPIO_Init(&Btn4);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI2, ENABLE);


	Btn5.pGPIOx = GPIOD;
	Btn5.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
	Btn5.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RT;
	Btn5.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn5.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;
	GPIO_PClkControl(GPIOD, ENABLE);
	GPIO_Init(&Btn5);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);
}

void Init_GPIO_Leds(void)
{
	memset(&Led, 0, sizeof(Led));

	Led.pGPIOx = GPIOB;
	Led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
	Led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_PClkControl(GPIOB, ENABLE);
	GPIO_Init(&Led);
}

// I2C2_SCL PF1
// I2C2_SDA PF0
// Each pin (master and slave) must be connected to the same bus, one for SCL and another for SDA
// Each bus must be powered by VCC (3.3V) with a resistor of 5kOhm


void Init_I2C2(void)
{
	GPIO_Handle_t I2C_SCL, I2C_SDA;

	/*Note : Internal pull-up resistors are used */

	I2C_SCL.pGPIOx = GPIOF;
	I2C_SCL.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	I2C_SCL.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
	I2C_SCL.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	I2C_SCL.GPIO_PinConfig.GPIO_PinAltFunMode = 4;
	I2C_SCL.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	I2C_SCL.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	GPIO_Init(&I2C_SCL);

	I2C_SDA.pGPIOx = GPIOF;
	I2C_SDA.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	I2C_SDA.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
	I2C_SDA.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	I2C_SDA.GPIO_PinConfig.GPIO_PinAltFunMode = 4;
	I2C_SDA.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	I2C_SDA.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	GPIO_Init(&I2C_SDA);

	I2C2Handle.pI2Cx = I2C2;
	I2C2Handle.I2C_Config.I2C_ACKControl = I2C_ACK_ENABLE;
	I2C2Handle.I2C_Config.I2C_DeviceAddress = MASTER_ADDR;
	I2C2Handle.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;
	I2C2Handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_FM400k;
	I2C_Init(&I2C2Handle);
}

int main(void)
{
	Init_GPIO_Buttons();

	Init_GPIO_Leds();

	Init_I2C2();
	// Don't forget to enable I2C
	I2C_PControl(I2C2, ENABLE);

	uint8_t emergency;

	while (1)
	{
		delay();
		I2C_MasterReceiveData(&I2C2Handle, &emergency, 1, SLAVE_ADDR, I2C_DISABLE_SR);
		GPIO_WriteToOutputPin(Led.pGPIOx, Led.GPIO_PinConfig.GPIO_PinNumber, emergency);
	}
}

// Btn1 (8), Btn5 (7)
void EXTI9_5_IRQHandler(void)
{
	if (EXTI->PR & (0x1U << 8))
	{
		GPIO_IRQHandling(8);
		//toggle led
		on1 ^= 0x1U << 0;
		I2C_MasterSendData(&I2C2Handle, &on1, 1, SLAVE_ADDR, 0);
	}

	if (EXTI->PR & (0x1U << 7))
	{
		GPIO_IRQHandling(7);
		//toggle led
		on5 ^= 0x1U << 0;
		I2C_MasterSendData(&I2C2Handle, &on5, 1, SLAVE_ADDR, 0);
	}
	delay();
}

// Btn2 (10), Btn3 (12)
void EXTI15_10_IRQHandler(void)
{
	if (EXTI->PR & (0x1U << 10))
	{
		GPIO_IRQHandling(10);
		//toggle led
		on2 ^= 0x1U << 0;
		I2C_MasterSendData(&I2C2Handle, &on2, 1, SLAVE_ADDR, 0);
	}

	if (EXTI->PR & (0x1U << 12))
	{
		GPIO_IRQHandling(12);
		//toggle led
		on3 ^= 0x1U << 0;
		I2C_MasterSendData(&I2C2Handle, &on3, 1, SLAVE_ADDR, 0);
	}
	delay();
}

// Btn4 (2)
void EXTI2_IRQHandler(void)
{
	if (EXTI->PR & (0x1U << 2))
	{
		GPIO_IRQHandling(2);
		//toggle led
		on4 ^= 0x1U << 0;
		I2C_MasterSendData(&I2C2Handle, &on4, 1, SLAVE_ADDR, 0);
	}
	delay();
}

