/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f429xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MASTER_ADDR		0x60U
#define SLAVE_ADDR		0x01U

void delay(uint32_t ms)
{
	// 1s -> 16MHz
	// 1ms -> 1,6KHz
	uint32_t i = ms*1600;
	for (; i > 0; i--);
}

// Data transfer
// [7:4]	not used
// [3:1]	led number
// [0]		on or off

GPIO_Handle_t Led1, Led2, Led3, Led4, Led5;
I2C_Handle_t I2C2Handle;

// Led1		PD3
// Led2		PE2
// Led3		PE5
// Led4		PF7
// Led5		PG1

void Init_GPIO_Leds(void)
{
	memset(&Led1, 0, sizeof(Led1));
	memset(&Led2, 0, sizeof(Led2));
	memset(&Led3, 0, sizeof(Led3));
	memset(&Led4, 0, sizeof(Led4));
	memset(&Led5, 0, sizeof(Led5));

	Led1.pGPIOx = GPIOD;
	Led1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_3;
	Led1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_PClkControl(GPIOD, ENABLE);
	GPIO_Init(&Led1);

	Led2.pGPIOx = GPIOE;
	Led2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_2;
	Led2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_PClkControl(GPIOE, ENABLE);
	GPIO_Init(&Led2);

	Led3.pGPIOx = GPIOE;
	Led3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	Led3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led3.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_PClkControl(GPIOE, ENABLE);
	GPIO_Init(&Led3);

	Led4.pGPIOx = GPIOF;
	Led4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
	Led4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led4.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_PClkControl(GPIOF, ENABLE);
	GPIO_Init(&Led4);

	Led5.pGPIOx = GPIOG;
	Led5.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	Led5.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led5.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led5.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led5.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	GPIO_PClkControl(GPIOG, ENABLE);
	GPIO_Init(&Led5);
}

// I2C2_SCL PF1
// I2C2_SDA PF0

void Init_I2C2(void)
{
	GPIO_Handle_t I2C_SCL, I2C_SDA;

	/*Note : Internal pull-up resistors are used */

	I2C_SCL.pGPIOx = GPIOF;
	I2C_SCL.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	I2C_SCL.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
	I2C_SCL.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	I2C_SCL.GPIO_PinConfig.GPIO_PinAltFunMode = 4;
	I2C_SCL.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	I2C_SCL.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	GPIO_Init(&I2C_SCL);

	I2C_SDA.pGPIOx = GPIOF;
	I2C_SDA.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	I2C_SDA.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
	I2C_SDA.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	I2C_SDA.GPIO_PinConfig.GPIO_PinAltFunMode = 4;
	I2C_SDA.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	I2C_SDA.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	GPIO_Init(&I2C_SDA);


	I2C2Handle.pI2Cx = I2C2;
	I2C2Handle.I2C_Config.I2C_ACKControl = I2C_ACK_ENABLE;
	I2C2Handle.I2C_Config.I2C_DeviceAddress = SLAVE_ADDR;
	I2C2Handle.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;
	I2C2Handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_FM400k;
	I2C_Init(&I2C2Handle);
}

int main(void)
{
	Init_GPIO_Leds();

	Init_I2C2();

	// Don't forget to enable I2C
	I2C_PControl(I2C2, ENABLE);

	// Enable ACKing
	I2C_ManageAcking(I2C2, I2C_ACK_ENABLE);

	// Enable interrupts
	I2C_IRQInterruptConfig(IRQ_NO_I2C2_EV, ENABLE);
	I2C_IRQInterruptConfig(IRQ_NO_I2C2_ER, ENABLE);

	// Enable callback
	I2C_SlaveEnableDisableCallbackEvents(I2C2, ENABLE);


	while (1);
}

void I2C2_EV_IRQHandler(void)
{
	I2C_EV_IRQHandling(&I2C2Handle);
}


void I2C2_ER_IRQHandler(void)
{
	I2C_ER_IRQHandling(&I2C2Handle);
}

uint8_t data = 0;

void I2C_ApplicationEventCallback(I2C_Handle_t *pI2CHandle,uint8_t AppEv)
{
	if(AppEv == I2C_EV_DATA_REQ)
	{
		// Master wants data
		//TODO not used in this example
	} else if (AppEv == I2C_EV_DATA_RCV)
	{
		// Master send data to slave, must read it
		data = I2C_SlaveReceiveData(I2C2);
	} else if (AppEv == I2C_ERROR_AF)
	{
		// Master send NACK, don't send more data
		//TODO not used in this example because slave isn't transmitting
	} else if (AppEv == I2C_EV_STOP)
	{
		// Master send data to slave and it has ended.
		uint8_t led = data >> 1;
		uint8_t on = data & 0x1U;
		switch (led)
		{
		case 0:
			GPIO_WriteToOutputPin(Led1.pGPIOx, Led1.GPIO_PinConfig.GPIO_PinNumber, on);
			break;
		case 1:
			GPIO_WriteToOutputPin(Led2.pGPIOx, Led2.GPIO_PinConfig.GPIO_PinNumber, on);
			break;
		case 2:
			GPIO_WriteToOutputPin(Led3.pGPIOx, Led3.GPIO_PinConfig.GPIO_PinNumber, on);
			break;
		case 3:
			GPIO_WriteToOutputPin(Led4.pGPIOx, Led4.GPIO_PinConfig.GPIO_PinNumber, on);
			break;
		case 4:
			GPIO_WriteToOutputPin(Led5.pGPIOx, Led5.GPIO_PinConfig.GPIO_PinNumber, on);
			break;

		}
	}
}
