/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f429xx.h"
#include "stm32f429xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay()
{
	for (volatile int i = 0; i < 500000; i++);
}

int main(void)
{
	GPIO_Handle_t Btn1, Btn2, Btn3, Btn4, Btn5;
	GPIO_Handle_t Led1, Led2, Led3, Led4, Led5;

	Btn1.pGPIOx = GPIOA;
	Btn1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	Btn1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	Btn1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Btn1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PD;

	GPIO_PClkControl(GPIOA, ENABLE);
	GPIO_Init(&Btn1);

	Led1.pGPIOx = GPIOB;
	Led1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_7;
	Led1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	Led1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Led1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Led1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_PClkControl(GPIOB, ENABLE);
	GPIO_Init(&Led1);

	while (1)
	{
		uint8_t value = GPIO_ReadFromInputPin(&Btn1);
		GPIO_WriteToOutputPin(&Led1, value);
		delay();
	}
}
